# Generated by Django 5.1.3 on 2025-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_album_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='None', upload_to='albumcovers'),
            preserve_default=False,
        ),
    ]
