# Generated by Django 5.1.3 on 2025-03-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
