# Generated by Django 5.1.3 on 2025-03-20 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_remove_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
