# Generated by Django 5.1.3 on 2025-03-20 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_rewiew_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiew',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
