# Generated by Django 5.1.3 on 2025-03-28 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
        migrations.AddField(
            model_name='request',
            name='datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
