# Generated by Django 5.1.3 on 2025-03-28 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_remove_request_date_request_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
